### ISSUE TITLE
Tor git issue

### ISSUE THREAD

**Issue by avaan** [iCepa/Tor.framework#1]
Hi,

I am facing below issue when I try to clone your code,

fatal: unable to access 'https://git.torproject.org/tor.git/': Server aborted the SSL handshake

i could not able to trouble shoot the issue. let me know how did you clone tor git.

**Comment by conradev** [comment]
It seems that the Tor Project's git and gitweb server is down. You could try pointing the submodule to a mirror!

**Comment by avaan** [comment]
@conradev yes you are right. it looks like this link is blocked here. 
If you have Tor.Framework can you upload here please. As I am not able to build it. Thanks.

**Comment by avaan** [comment]
Finally i was able to compile your project....

**Comment by avaan** [comment]
As I could not use "github "iCepa/Tor.framework" "e30f2a4974a1464ecb4c53a1fce000e4206633ed"" as it is giving tor access denied error. 

I build your project and imported all required framework and libraries to my project. But when I running my project I am getting below error

dyld: Library not loaded: @rpath/Tor.framework/Tor
  Referenced from: /private/var/mobile/Containers/Bundle/Application/E1D6BBC7-9685-4FED-8A46-FEB42E6E1C13/xxxx.app/xxx
  Reason: image not found

can you please tel me was was i am doing wrong here.

**Comment by avaan** [comment]
getting below error,

Feb 17 14:59:08.054 [notice] Tor v0.2.6.10 running on Darwin with Libevent 2.0.22-stable, OpenSSL 1.0.2d and Zlib 1.2.5.
Feb 17 14:59:08.055 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Feb 17 14:59:08.056 [notice] Configuration file "/private/var/mobile/Containers/Data/Application/6AFFEFD6-D336-4AA8-A88C-322089C54C37/.torrc" not present, using reasonable defaults.

**Comment by conradev** [comment]
Awesome, glad to hear! Let me know if you run across any issues.

**Comment by avaan** [comment]
Hi... sorry to bother you.
While running my app I am getting below errors. 

Feb 18 10:11:15.489 [notice] Tor v0.2.6.10 running on Darwin with Libevent 2.0.22-stable, OpenSSL 1.0.2d and Zlib 1.2.5.
Feb 18 10:11:15.490 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Feb 18 10:11:15.491 [notice] Configuration file "/private/var/mobile/Containers/Data/Application/EB4214A6-01A7-406D-8F32-BEF21DD4DBF4/.torrc" not present, using reasonable defaults.
Feb 18 10:11:15.691 [notice] Opening Socks listener on 127.0.0.1:9050
Feb 18 10:11:15.710 [warn] Permissions on directory /var/mobile/Containers/Data/Application/EB4214A6-01A7-406D-8F32-BEF21DD4DBF4/Documents are too permissive.
Feb 18 10:11:15.711 [warn] Before Tor can create a control socket in "/var/mobile/Containers/Data/Application/EB4214A6-01A7-406D-8F32-BEF21DD4DBF4/Documents/control_port", the directory "/var/mobile/Containers/Data/Application/EB4214A6-01A7-406D-8F32-BEF21DD4DBF4/Documents" needs to exist, and to be accessible only by the user account that is running Tor.  (On some Unix systems, anybody who can list a socket can connect to it, so Tor is being careful.)
Feb 18 10:11:15.713 [notice] Closing partially-constructed Socks listener on 127.0.0.1:9050
Feb 18 10:11:15.715 [warn] Failed to parse/validate config: Failed to bind one of the listener ports.
Feb 18 10:11:15.716 [err] Reading config failed--see warnings above.

trying to find the cause.....
