### ISSUE TITLE
By default use dist packages of OpenSSL, libevent, and Tor to remove need for autotools

### ISSUE THREAD

**Issue by chrisballinger** [iCepa/Tor.framework#14]
I want to include Tor.framework as a dependency of another module (TorXPCService) and don't want to require consumers to install autotools. It would also speed up clones because entire history of those modules isn't needed.

What do you think?

**Comment by conradev** [comment]
I like this idea. I just pushed 1d1d38e68581ba7cd12903a0a5bfd87a9e02731d which makes submodule clones shallow (as of `git` 2.10) in the meantime, but I would love to remove the dependency on `autotools`.

OpenSSL doesn't rely on it at all, but `libevent` and `tor` do. Would we make the build scripts download and unpack the source code?

Part of me likes being having all the source code inside of `git`, but I can also see the project downloading and verifying the tarballs.

**Comment by chrisballinger** [comment]
This is what we do over here: https://github.com/ChatSecure/CPAProxy/blob/master/scripts/build-tor.sh#L4

Turns out retry is pretty critical on Travis because it sometimes times out. I was never able to get the GPG verification to work via Travis, so I think it would possibly be better to just verify that the SHA256 matches, but it makes updating the build versions a bit more annoying.

**Comment by tladesignz** [comment]
There's binary distributions since quite a while which are usable through Carthage and Cocoapods. I guess, that's suitable enough, so I'll close this.
