### ISSUE TITLE
TORConfiguration controlSocket issue with spaces in path

### ISSUE THREAD

**Issue by chrisballinger** [iCepa/Tor.framework#16]
I think any of the TORConfiguration options with paths/urls can break if there are spaces in them

**Comment by chrisballinger** [comment]
Ah yeah, I forgot to mention I added escaped quotes but it still didn't work. (This is using 0.2.9.9)

**Comment by conradev** [comment]
Oh, oops! This is because `ControlSocket` is actually deprecated and doesn't support spaces (see ticket). It really should be using `ControlPort` with the `unix:` prefix.

**Comment by chrisballinger** [comment]
That explains it. :)

Thanks!

**Comment by conradev** [comment]
Closing because #17
