### ISSUE TITLE
Use new official Tor embedding API tor_api.h in 0.3.3.6

### ISSUE THREAD

**Issue by chrisballinger** [iCepa/Tor.framework#36]
* https://trac.torproject.org/projects/tor/ticket/23684
* https://blog.torproject.org/tor-0336-released-new-stable-series

**Comment by tladesignz** [comment]
Just stumbled over this in my old unanswered emails list.
We're now at Tor 0.3.5.8.
Do you want to check, if it's now like you wanted it?
