### ISSUE TITLE
App killed after phone lock

### ISSUE THREAD

**Issue by SwenVanZanten** [iCepa/Tor.framework#37]
My app gets killed when the phone gets locked and unlocked and open the app again.

The following error get raised:
```
 [] nw_socket_get_input_frames recvmsg(fd 18, 1024 bytes) [57: Socket is not connected]
Aug 18 21:17:30.000 [warn] Warning from libevent: Error Socket is not connected (57) while reading request.
```

This doesn't happen on the simulator though.
There it's all huffy and fluffy.

Also I included the framework in the repo, cause it doesn't compile no more..
Not sure what changed from the first time I build it but it doesn't seem to work no more.
I'll try to find what the problem there is.. but might file an issue for that too 😅 

Reproduction:
* Compile project on device: https://github.com/vergecurrency/vIOS
* Lock your phone
* Unlock your phone and enter the app
* See error.

**Comment by tladesignz** [comment]
This is to be expected. The Tor version, Tor.framework currently works with, cannot survive a device suspension and cannot be restarted in-process.

However, there are changes in the latest Tor, which let us restart Tor in-process. Chances are good that there will be a new version of [OnionBrowser](https://github.com/OnionBrowser/OnionBrowser) in 2019, during which' development, Tor.framework will also be overhauled and updated to the latest Tor version and gets support added for restarting Tor.

**Comment by tladesignz** [comment]
Sorry, not yet. Funding is still negotiated. However, it will be top priority when that is out of the way.
