### ISSUE TITLE
Build failing with Carthage & Xcode 10.1 (10B61)

### ISSUE THREAD

**Issue by sighmon** [iCepa/Tor.framework#42]
macOS 10.14.3
Xcode 10.1 (10B61)

Steps:
* brew install automake autoconf libtool gettext
* git clone git@github.com:iCepa/Tor.framework
* cd Tor.framework
* git submodule init
* git submodule update
* carthage build --no-skip-current --platform iOS

Failure:
```bash
$ carthage build --no-skip-current --platform iOS
*** xcodebuild output can be found in /var/folders/jx/yr801c_w8xj3860059bj5rtr0000gp/T/carthage-xcodebuild.U5tvVH.log
*** Skipped building xcconfigs due to the error:
Dependency "xcconfigs" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/jspahrsummers/xcconfigs/issues/new
*** Building scheme "Tor-iOS" in Tor.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/xxx/Coding/iOS/Tor.framework/Tor.xcodeproj -scheme Tor-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/jx/yr801c_w8xj3860059bj5rtr0000gp/T/Tor.framework SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/xxx/Coding/iOS/Tor.framework)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/jx/yr801c_w8xj3860059bj5rtr0000gp/T/carthage-xcodebuild.U5tvVH.log
```

End of that log file:
```bash
The following build commands failed:
	Ld /Users/xxx/Library/Developer/Xcode/DerivedData/Tor-dugfavzqljrdqmfupfmxtrcxizes/Build/Intermediates.noindex/ArchiveIntermediates/Tor-iOS/IntermediateBuildFilesPath/Tor.build/Release-iphoneos/Tor-iOS.build/Objects-normal/arm64/Tor normal arm64
(1 failure)
```

**Comment by tladesignz** [comment]
Ok, so I have the exact same setup.

I can build without problems from a fresh clone.

I also did it on a second computer, where I had to set up carthage, all the brew dependencies and Xcode. Works as expected. Only difference was the MacOS: High Sierra 10.13.6 instead of Mojave 10.14.3

Sorry, I need more information to help you. Please check the log for further info.

**Comment by sighmon** [comment]
@tladesignz I thought it might have something to do with me running Xcode 10.2 beta, so ran `xcode-select --install` again. Then `brew config` showed:

```bash
$ brew config
HOMEBREW_VERSION: 2.0.1
Clang: 10.0 build 1000
macOS: 10.14.3-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
```

But unfortunately it still failed to build.

Here's the full log:
https://gist.github.com/sighmon/a0d13deea8e439324775f2d1c3c49631

**Comment by tladesignz** [comment]
Ah-hm. So you *didn't* use Xcode 10.1 but 10.2 as you originally said you did? Sorry, you're on your own with that. Your setup is probably botched up. Remove everything, reinstall, clean all builds, rebuild.

Your log doesn't show any error, btw.
