### ISSUE TITLE
Initial setup failing

### ISSUE THREAD

**Issue by FontaineDenton** [iCepa/Tor.framework#44]
Hi trying to carry out the initial set up, please see my errors:

`DIRECT-8A-HP-OfficeJet-4650:~ peter$ cd Tor.framework

DIRECT-8A-HP-OfficeJet-4650:Tor.framework peter$ git submodule init

DIRECT-8A-HP-OfficeJet-4650:Tor.framework peter$ git submodule update

Cloning into '/Users/peter/Tor.framework/Tor/tor'...
fatal: unable to access 'https://git.torproject.org/tor.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to git.torproject.org:443 
fatal: clone of 'https://git.torproject.org/tor.git' into submodule path '/Users/peter/Tor.framework/Tor/tor' failed
Failed to clone 'Tor/tor'. Retry scheduled
Cloning into '/Users/peter/Tor.framework/Tor/tor'...
fatal: unable to access 'https://git.torproject.org/tor.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to git.torproject.org:443 
fatal: clone of 'https://git.torproject.org/tor.git' into submodule path '/Users/peter/Tor.framework/Tor/tor' failed
Failed to clone 'Tor/tor' a second time, aborting`

**Comment by tladesignz** [comment]
Sorry, you clearly have an issue with your git installation or network stack. That has nothing to do with `Tor.framework`.
This is not the right area to debug general computer problems.
