### ISSUE TITLE
gRPC connecting over Tor

### ISSUE THREAD

**Issue by JimmyMow** [iCepa/Tor.framework#52]
Hi. I am trying to allow users of my application to connect to a server over Tor. We are using gRPC, and from my quick research, there are some issues in accomplishing this. It seems that the problem is that this library is using NSURLSession API and the grpc library is using CFStream API. It seems there is also a potential issue with Tor and `http/2`.

I was wondering if anyone has connected over Tor using gRPC successfully or if anyone had any helpful pointers for me in trying to accomplish this. Would be much appreciated!

**Comment by FontaineDenton** [comment]
Even when using NSURLSession making JSON-RPC calls over http on device always returns "Internet not connected" error for hidden services yet works great for .com urls. Very frustrating. I wonder if the issues are related?

**Comment by tladesignz** [comment]
Hey, sorry, that nobody ever got back to you. You might want to check out #54, you might find more info there. Anyway, I'll close this. Feel free to reopen, if you have questions.
