### ISSUE TITLE
Invalid CFBundleVersion number

### ISSUE THREAD

**Issue by Jasonvdb** [iCepa/Tor.framework#60]
Apps using version `400.6.3` are unable to be submitted to the app store because of an invalid number for the `CFBundleVersion`.

<img width="622" alt="Screenshot 2020-03-06 at 08 17 29" src="https://user-images.githubusercontent.com/5300488/76057710-f2ac8080-5f82-11ea-858d-dcbef73565e9.png">

Seems to be a problem with the method of incrementing the version in https://github.com/iCepa/Tor.framework/blob/master/Tor/version.sh

Have a suspicion the bug came in with this commit https://github.com/iCepa/Tor.framework/commit/6b0c7edb330a3734a6e0c34b662a0af27d884fb8 but don't understand it's reason well enough to make a change.

**Comment by Fonta1n3** [comment]
I am getting this too after updating... thank goodness you raised this issue. I was going insane.

**Comment by tladesignz** [comment]
1. The mentioned commit made it possible to actually build on a non-US-localized system. Nothing else.

2. Problem was, that I used a time slightly in the future here when I did the release build:
https://github.com/iCepa/Tor.framework/blob/8fc455b6ad72da62135b2384e6eaa8505daf7672/Tor/version.sh#L24
That leads to a negative number:
https://github.com/iCepa/Tor.framework/blob/8fc455b6ad72da62135b2384e6eaa8505daf7672/Tor/version.sh#L36

I re-built and uploaded the release anew. Going to fix the script. 

Re-download Tor.framework with Carthage or Cocoapods and you should be good!
Make sure to clear Carthage's caches:

```bash
project$ rm -rf ~/Library/Caches/org.carthage.CarthageKit
project$ rm -r Carthage
```

(or analogue if you use Cocoapods)

Thanks for catching this and sorry for the inconvenience!

**Comment by Jasonvdb** [comment]
Awesome thanks for the quick fix!
