### ISSUE TITLE
Tor resignation not working with 0.4.2.7

### ISSUE THREAD

**Issue by Fonta1n3** [iCepa/Tor.framework#62]
I am using a similar method to OnionBrowser as per [#56](https://github.com/iCepa/Tor.framework/issues/56) for resigning the tor thread which had been working fine, yet with the latest update the tor thread stays intact and does not exit at all. Any ideas why that may be? Are you able to replicate that issue?

**Comment by SwenVanZanten** [comment]
Can confirm the problem.
Looks like TorController.disconnect() isn't working anymore.

**Comment by tladesignz** [comment]
Hey! Thanks a ton for catching this!
I'm in discussion with Tor folks: https://trac.torproject.org/projects/tor/ticket/33837#comment:18

We'll see what happens. For now: Stay with 0.4.0.6!

**Comment by tladesignz** [comment]
Moved bug to https://trac.torproject.org/projects/tor/ticket/33924.

**Comment by tladesignz** [comment]
I got one step further, however now there's a new issue: After restart, testing with Onion Browser, OB explodes with all sorts of `EXC_BAD_ACCESS` crashes, even when just trying to print a debug message. Will work with Tor folks on it.

**Comment by tladesignz** [comment]
Ok, finally resolved. I just released a new v403.5.1 containing Tor 0.4.3.5 which fixes all problems. Enjoy!

**Comment by SwenVanZanten** [comment]
Awesome! Thank you for letting know 💪
