### ISSUE TITLE
Building arm64 for new macs

### ISSUE THREAD

**Issue by n690rp** [iCepa/Tor.framework#67]
Nick and crew,

we have libevent-2.1.12 and openssl-1.1.1h building arm64 and x86_64 for use in new Mac universal.

libevent is straightforward, openssl we add this to Configurations/10-main.conf

    "darwin64-arm64-cc" => {
        inherit_from     => [ "darwin-common", asm("aarch64_asm") ],
        CFLAGS           => add("-Wall"),
        cflags           => add("-arch arm64"),
        lib_cppflags     => add("-DL_ENDIAN"),
        bn_ops           => "SIXTY_FOUR_BIT_LONG",
        perlasm_scheme   => "macosx",
    },

In build script:
./Configure enable-rc5 darwin64-arm64-cc no-asm no-async --openssldir...

I am not yet familiar enough to try and submit a pull request, but is there is interest in this?

**Comment by tladesignz** [comment]
@n690rp, this is very helpful, thank you very much!

(BTW: Tor.framework isn't an official part of Tor Project, but we're in close contact. I already brought this to their attention: https://gitlab.torproject.org/tpo/core/tor/-/issues/40198)
