### ISSUE TITLE
How to build standalone static framework from pod?

### ISSUE THREAD

**Issue by DanGould** [iCepa/Tor.framework#73]
Carthage output a nice Tor.framework folder that I could bind to from C#. I've always taken this output to bind calls to the Objective-c  and and reference the output Tor executable: https://github.com/chaincase-app/Xamarin.iOS.Tor

On pure_pod, I haven't figured out how to create this output executable. The scripts seem tailored to the _Pods environment and don't appear to build the framework on their own, nor do I see an option to build the framework so in xcode from the _Pods or Example environments. I haven't gotten Example/Tor to build because it says Tor/NSBundle+GeoIP.h file not found even after running `pod install`

How can we build a static Tor.framework to the latest version? The cocoapods release instructions don't seem to do this.

**Comment by tladesignz** [comment]
All the information is in the [README](https://github.com/iCepa/Tor.framework/blob/pure_pod/README.md).

If you can't handle a dynamic framework, as the default Podspec produces, you might want to try the experimental static library podspec.

If you never used CocoaPods, help yourself to knowledge here: https://cocoapods.org

If this is all unsuitable to you, you're welcome to send pull requests for the old Carthage-based branch: https://github.com/iCepa/Tor.framework/
You should use the new `--use-xcframeworks` feature of Carthage to get compatible with Apple Silicon.

However, I'm done with Carthage. It's just highly annoying and awfully underdocumented. CocoaPods is not ideal either for a package like Tor.framework, as it forces the consumers to have all the build tools ready themselves, but it causes way less issues and is better documented and supported.
