### ISSUE TITLE
Building Tor.framework on M1 arm64 Xcode 14

### ISSUE THREAD

**Issue by EETagent** [iCepa/Tor.framework#74]
First of all, I would like to thank you for a very useful project for macOS and the Obj-C ecosystem.

I am unable to build a framework on arm64 devices with Xcode 14. Generated libraries like `libevent.a `or `libcrypto.a` are ok arm64 bytecode, it is possible to simply check their validity by linking with a c file. `libtor.a` as a single library fails linking and is invalid.

I don't have a similar problem on an x86_64 Mac with Xcode 13, where the universal libraries are generated correctly.

<img width="920" alt="Snímek obrazovky 2022-08-25 v 11 18 31" src="https://user-images.githubusercontent.com/20557318/186627291-7426c22c-4315-4dea-a46b-7f0d83105e00.png">

<img width="865" alt="Snímek obrazovky 2022-08-25 v 11 14 30" src="https://user-images.githubusercontent.com/20557318/186627310-e620eae3-004e-43b7-8410-31b3c60bdae5.png">

<img width="998" alt="image" src="https://user-images.githubusercontent.com/20557318/186628819-b0ada78e-7f05-462c-a450-f1c211c8f31d.png">

Since this is probably a bug caused by the build system of the tor project, I don't really know how to fix the problem.

**Comment by tladesignz** [comment]
Did you use the [Pure Pod Version](https://github.com/iCepa/Tor.framework/tree/pure_pod)?

**Comment by EETagent** [comment]
This is pure_pods branch, latest version 407.8.2

**Comment by EETagent** [comment]
@tladesignz New version works perfectly, closing the issue.

Thanks 👍

**Comment by tladesignz** [comment]
I didn't realise - you already used Xcode 14 back then. Must have been a beta, I guess?

Well, anyway, after I upgraded I had the same problem, soooo... always happy to help! 🤷🤪
