### ISSUE TITLE
Build failed (libor)

### ISSUE THREAD

**Issue by dakesson** [iCepa/Tor.framework#8]
All dependencies installed through brew,  macOS 10.12.1 , Xcode 8.1

Seems this can be connected to OpenSSL but coulden't resolve it. Any help is much appreciated

https://jpst.it/PRUg

**Comment by conradev** [comment]
Hi @dakesson! I would love to help figure this out.

The log you posted isn't the full log. If you could navigate to the last tab in Xcode (`⌘+8`), select `By Time`, click on the top entry, click `Save…` in the top right, and attach it to a Github comment I can give this a good look!

**Comment by dakesson** [comment]
Thanks for the response, here's the full log:
https://dl.dropboxusercontent.com/u/10700891/carthage-xcodebuild.E3Ru4k.log

**Comment by conradev** [comment]
Awesome. The actual error in there is this (when building `tor-static-iOS` for `arm64`):

```
checking for libevent directory... configure: WARNING: We found the libraries for libevent, but we could not find the C header files.  You may need to install a devel package.
```

Could you try again and see if there is a file at `Tor/tor/config.log`? That file would have the specific build error that triggered that `configure` error.

**Comment by dakesson** [comment]
I cannot find any config.log, however I found a dgph file that might be of help
https://dl.dropboxusercontent.com/u/10700891/dgph

I tried to manually execute Carthage/Checkouts/Tor.framework/Tor/libevent.sh but got missing ./autogen.sh guess that script wasn't intended to be executed like that.

**Comment by conradev** [comment]
@dakesson, correct, the script is really meant to be executed by Xcode.

If you open the Xcode project and manually build the `tor-static-iOS` scheme, it should leave a `config.log` in `Tor/tor/config.log`. I'm not sure what would be removing it, but it might be the `make distclean` in `tor.sh`.

**Comment by dakesson** [comment]
I used carthage to include it into an existing project which I can build with no problems.

Went into carthage checkouts directory and open the tor project and built tor-static-ios from xcode and i got "Build successful", however it did also say "8 issues". Full log is posted here:

https://dl.dropboxusercontent.com/u/10700891/config.log

**Comment by conradev** [comment]
Awesome, thanks for the `config.log`! My `libevent` configure patch wasn't applied.

57c906476ea6e87198c2be3798ddc17000902b3e should fix your issue from happening in the future, but you will need to run
```
git submodule update -f --checkout && git submodule foreach git clean -f
```
in the git repo after pulling.

**Comment by dakesson** [comment]
New try, building tor-static-iOS gives the following:

https://dl.dropboxusercontent.com/u/10700891/config2.log

Is there anything obvious I'm missing?

**Comment by conradev** [comment]
@dakesson are you still experiencing issues with the latest `master`? Feel free to re-open this if you are, but I am going to close it for now.
