### ISSUE TITLE
Arti Import

### ISSUE THREAD

**Issue by maxime-guerin-biprep** [iCepa/Tor.framework#85]
Hello,
I am trying to use arti in ios.
It seems that i cant import <Tor/TORArti.h> where i can import <Tor/TORConfiguration.h>
Maybe the USE_ARTI is not set in the pod.

I need to have a socks server, maybe i dont need arti ?

**Comment by tladesignz** [comment]
Sorry, this is neither the place for programming training, nor consulting. You need to make sure to include the correct subspec. If you don't know what that is, consult the CocoaPods documentation.
