### ISSUE TITLE
`Library 'crypto' not found` when building from pure pod

### ISSUE THREAD

**Issue by Fonta1n3** [iCepa/Tor.framework#88]
I am trying to use the pure pod but am getting some issues building it in Xcode.

Currently I am getting `Library 'crypto' not found` in Xcode after running `pod install` successfully.

my pod file looks like this:
```
# Uncomment the next line to define a global platform for your project
platform :macos, '14.0'

target 'TorConnect' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Tor', :podspec => 'https://raw.githubusercontent.com/iCepa/Tor.framework/pure_pod/TorStatic.podspec'

  # Pods for TorConnect

end
```

Any tips on troubleshooting would be appreciated.

**Comment by tladesignz** [comment]
You combined CocoaPods dynamic frameworks setting with the static build of Tor.framework... (See comment in your Podfile)

If you don't need the static build, I recommend using the dynamic framework.

In that case, you can just use the published build:

```ruby
  pod 'Tor'
```

**Comment by Fonta1n3** [comment]
When I do that I get `Framework 'Tor' not found`.

I have tried a few things to troubleshoot, like clearing the cocoa pod cache, `pod deintegrate`, deleting derived data etc.. but am not sure what the issue is. I have other projects that use the framework without issues.

**Comment by Fonta1n3** [comment]
It works after some tweaking of Xcode settings on a different machine with a fresh Xcode project, it feels like something is cached that is preventing it from building/compiling properly on the other machine. Not sure what to do other then delete the cocoa pods cache, reboot etc.

**Comment by tladesignz** [comment]
You can either use the dynamic framework version (which is also the one which is distributed), when your project relies on dynamic frameworks.

Or you can use the static version from that special PodSpec file, when your project is set up to use static libraries.

You cannot mix both.

Some other dependencies might have problems with either being a dynamic framework or a static library. I cannot help you with finding the right combination for your project, though. That's something you need to figure out for yourself. Good luck!

**Comment by Fonta1n3** [comment]
Right, for some reason I thought I needed the static but I was wrong. I am using dynamic frameworks, I was not able to replicate this issue so closing this out.
