### ISSUE TITLE
OpenSSL 1.1.X calls private APIs, fails iOS App Store validation

### ISSUE THREAD

**Issue by mtigas** [iCepa/Tor.framework#9]
Been testing a version of Onion Browser using Tor.framework over the past few days.

Recently got this when trying to push some test builds:

> **Non-public API usage:**
>
>    The app references non-public symbols in Frameworks/Tor.framework/Tor: _getcontext, _makecontext, _setcontext

Have any of us tried submitting something using Tor.framework since the recent dependency version bumps?

Looks like it comes from OpenSSL. It's limited to one little part of OpenSSL for [asynchronous jobs](https://www.openssl.org/docs/man1.1.0/crypto/ASYNC_is_capable.html). culprits are in [async_posix.c](https://github.com/openssl/openssl/blob/OpenSSL_1_1_0-stable/crypto/async/arch/async_posix.c), [async_posix.h](https://github.com/openssl/openssl/blob/OpenSSL_1_1_0-stable/crypto/async/arch/async_posix.h)

I have [a hackish branch](https://github.com/iCepa/Tor.framework/compare/master...mtigas:openssl_1_1_0-iosprivateapis) that zeroes out the two files in question & prevents the header from being included. Just to test if it’ll pass a submission validation. This essentially just makes OpenSSL fall back to the `async_null` implementation where it does nothing (for platforms that don’t support async). Haven't tried resubmitting anything that builds like this yet (will try to do tonight), but that's there.

Anyway just opened this to flag it and see if anyone else has seen it (or something similar). There is also _probably_ a more elegant solution (config or something) that disables those bits better than my branch.

**Comment by conradev** [comment]
Considering I made the version bumps fairly recently, you're most likely the first to try! There are [similar things](https://github.com/iCepa/Tor.framework/blob/57c906476ea6e87198c2be3798ddc17000902b3e/Tor/tor.sh#L49-L52) in place for `tor`.

The elegant solution actually seems to just be passing `no-async` to OpenSSL's configure script 🎉. I'll throw it on a branch so you can test it.

**Comment by mtigas** [comment]
Looks like `no-async` (09b7c3489f30b206c15b409cbb0b4350d1bb1bb0) works great. Submitted just fine. 👍

**Comment by conradev** [comment]
Awesome! Merged 😄
