### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code error when updating to 408.11.2

### ISSUE THREAD

**Issue by Fonta1n3** [iCepa/Tor.framework#91]
I am getting the above error when updating to 408.11.2.

I have tried:
- reintegrating the pod
- manually deintegrating
- updating cocoapods
- deleting derived data
- clean build
- removing the pod and installing fresh
- updating xcode
- updating macOS
- cleaning the cocoa pod cache 

I am out of ideas.. The only other suggestion I saw was to `chmod +x ` on the `"${PODS_ROOT}/Target Support Files/Pods-FullyNoded/Pods-FullyNoded-frameworks.sh"` but I am not sure what the `PODS_ROOT` location is.

Any tips? Was working fine in prior version 408.10.1

Thanks for your help.

**Comment by tladesignz** [comment]
You will need to provide the *actual* error, which triggered this.

In Xcode's Drop-Down Menu:

View -> Navigators -> Reports

In the reports tab make sure "Local" is selected, not "Cloud".

The select the latest "Build" which is marked with a red X.

Then browse the log output for the actual error.

It should look something like this:

<img width="1761" alt="Bildschirmfoto 2024-07-04 um 12 23 01" src="https://github.com/iCepa/Tor.framework/assets/117089/e994cdc9-d6a5-478c-9724-e17030c5b887">

**Comment by Fonta1n3** [comment]
<img width="1440" alt="Screenshot 2024-07-04 at 15 58 04" src="https://github.com/iCepa/Tor.framework/assets/30832395/be3c8498-2ced-4df5-933e-713185858261">

The thing is I have unchecked "Based on dependency analysis", I have tried multiple options whilst cleaning the build and restarting Xcode. What is the correct setting?

<img width="1440" alt="Screenshot 2024-07-04 at 16 00 03" src="https://github.com/iCepa/Tor.framework/assets/30832395/dbb644f3-7ac6-4de6-a2a0-ee2a94f50172">

**Comment by Fonta1n3** [comment]
<img width="1440" alt="Screenshot 2024-07-04 at 22 33 10" src="https://github.com/iCepa/Tor.framework/assets/30832395/0be22f61-cdc4-4739-8472-4ff04a70e94a">

Now I'm getting this. A bit more helpful.

**Comment by Fonta1n3** [comment]
Somehow Xcode command line tools became uninstalled at some point on my machine which seems to have been the culprit here, working fine now. Thank you!

**Comment by tladesignz** [comment]
You're welcome!
